services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - 6379:6379
    # environment:
    #   - VALKEY_CONFIG=/etc/valkey/valkey.conf
    # volumes:
    #   - ./valkey.conf:/etc/valkey/valkey.conf
    # networks:
    #   - valkey_network
  qdrant:
    image: qdrant/qdrant
    
    ports:
      - 6333:6333
    # environment:
    #   - QDRANT_CONFIG=/etc/qdrant/qdrant.conf
    # volumes:
    #   - ./qdrant.conf:/etc/qdrant/qdrant.conf
    # networks:
    #   - qdrant_network